### ISSUE TITLE
Package project setup

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail-newsletter#1]
```[tasklist]
### Tasks
- [x] Package name
- [x] Package repository scaffolding
- [x] Continuous integration (GitHub Actions), including Python x Django x Wagtail compatibility testing matrix
- [x] pytest
- [x] pyright
- [x] Documentation scaffolding (Markdown in docs/ folder)
```

**Comment by mgax** [comment]
The documentation is set up with [Sphinx](https://www.sphinx-doc.org/) and [sphinx-wagtail-theme](https://sphinx-wagtail-theme.readthedocs.io/) and it gets built and hosted by [Read the Docs](https://readthedocs.org/): https://wagtail-newsletter.readthedocs.io/.

We need to set up a [webhook](https://docs.readthedocs.io/page/webhooks.html) to trigger builds automatically and I don't have the right permissions on this repo. @thibaudcolas could you please have a look? Thanks!

**Comment by thibaudcolas** [comment]
Read the Docs is now hooked up to GitHub, with their default integration. Tested in #13 that the builds now work correctly, for pull requests and for the `main` branch on merge.
