### ISSUE TITLE
Spikes: architecture decisions

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail-newsletter#2]
## Foundational elements

Specific points which will likely require further analysis early on in the project, relating to foundational elements.

```[tasklist]
### Tasks
- [x] Page type integration API: mixin vs. alternatives
- [x] Overview of project-level configuration / customization requirements (settings via inheritance, hooks, project-wide Django settings, etc)
```

## Email rendering

Architecture decisions relating to MJML / rendering of pages as email:

```[tasklist]
- [x] Approach for plain-text rendering
- [x] Approach for rich text rendering of custom rich text formats (text formatting, links, images, embeds)
- [x] MJML rendering integration: django-mjml command mode vs. server vs. mjml-python vs. alternatives
```

## Mailchimp integration

Architecture decisions relating to Mailchimp:

```[tasklist]
- [x] Requirements gathering for management of newsletter entry metadata / blurb / footer information
- [x] Approach to rendering of Mailchimp-driven required email content (required merge tags such as subscription management links).
- [x] Mailchimp RSS vs. Mailchimp API
- [x] Approach to fetching & selecting campaign recipients
- [x] Campaign sending & post-send metadata retrieval
```

**Comment by mgax** [comment]
I've copied the research notes into this gist: https://gist.github.com/mgax/deddd07d671f7abdd77125bdf9774875.
